TARGET =: clang
ARCHS = armv7 arm64

include theos/makefiles/common.mk

TOOL_NAME = ColendarWriter
ColendarWriter_FILES = main.mm
ColendarWriter_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tool.mk
